version: '2'

services:
    # basenode:
    #     build: ./base
    #     stdin_open: true
    #     tty: true
    masternode:
        build: ./master
        stdin_open: true
        tty: true
        ports:
            - "17557:7557"
            - "18002:8002"
        volumes:
            - /home/devel1/multichainDemo/docker-multichain/volumes/master/root/.multichain:/root/.multichain           
        environment:
            CHAINNAME: MyChain
            NETWORK_PORT: 7557
            RPC_PORT: 8002
            RPC_USER: multichainrpc
            RPC_PASSWORD: this-is-insecure-change-it
            RPC_ALLOW_IP: 0.0.0.0/0.0.0.0
            PARAM_TARGET_BLOCK_SIZE: target-block-time|30
            PARAM_ANYONE_CAN_CONNECT: anyone-can-connect|true
            PARAM_ANYONE_CAN_MINE: anyone-can-mine|true
    slavenode:
        build: ./node
        stdin_open: true
        tty: true
        ports:
            - "27557:7557"
            - "28002:8002"
        volumes:
            - /home/devel1/multichainDemo/docker-multichain/volumes/slave/root/.multichain:/root/.multichain               
        environment:
            CHAINNAME: MyChain
            NETWORK_PORT: 7557
            RPC_PORT: 8002
            RPC_USER: multichainrpc
            RPC_PASSWORD: this-is-insecure-change-it
            RPC_ALLOW_IP: 0.0.0.0/0.0.0.0
            PARAM_ANYONE_CAN_CONNECT: anyone-can-connect|true            
            MASTER_NODE: masternode
        links:
            - masternode
        depends_on:
            - masternode
    explorernode:
        build: ./explorer
        stdin_open: true
        tty: true
        ports:
            - "32750:2750"
            - "37557:7557"
            - "38002:8002"
        environment:
            CHAINNAME: MyChain
            NETWORK_PORT: 7557
            RPC_PORT: 8002
            RPC_USER: multichainrpc
            RPC_PASSWORD: this-is-insecure-change-it
            RPC_ALLOW_IP: 0.0.0.0/0.0.0.0
            MASTER_NODE: masternode
        links:
            - masternode
        depends_on:
            - masternode
